### ISSUE TITLE
Kopiowanie

### ISSUE THREAD

**Issue by fryzjer69** [thornag/tf-mapper#54]
Czy istnieje możliwość skopiowania pokoi ? Tzn np mam oddzielnie Tileę, a chciałbym ją przekleić do Imperium, czy nie ma gdzieś możliwośći użycia opcji kopiuj / wklej ?

**Comment by thornag** [comment]
Zaznacz pokoje (przeciagnij + SHIFT albo wyklikaj z CMD) i kliknij CMD+C, pozniej prawym myszy na mape i paste

**Comment by fryzjer69** [comment]
Ano, wlasnie nic sie nie wkleja.

**Comment by fryzjer69** [comment]
Czy moglbys to sprawdzic ? Bo nie wiem, czy ja robie to zle, czy po prostu jednak nie da sie przeklejac ?

**Comment by fryzjer69** [comment]
Ok, juz wiem czemu sie nie kopiowalo:

NIe kopiuje w momencie, gdy zaznaczysz tez jakiekolwiek labele.

Czy istnieje mozliwosc poprawienia tego, zeby mozna bylo kopiowac rowniez labele ?

**Comment by thornag** [comment]
Nope.
