### ISSUE TITLE
Import

### ISSUE THREAD

**Issue by fryzjer69** [thornag/tf-mapper#58]
Czy import plikow dbm z cmuda dziala ? Dostalem mape, ktora probowalem zaimportowac, ale po kliknieciu import wyswietla i pyta, ktory zone zaimportowac i potem juz nic sie nie dzieje ( program sie wiesza ) ?

**Comment by thornag** [comment]
To bylo super mocno experymentalne wiec jesli nie dziala z Twoja mapa to nie dziala ;)

**Comment by fryzjer69** [comment]
Rozumiem, 

Dzieki :)
